# Generated by Django 5.2.3 on 2025-06-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorp_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fluencyLevel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='motherLanguage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='targetLanguage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
