# Generated by Django 5.2.3 on 2025-07-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorp_api', '0002_user_fluencylevel_user_motherlanguage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unknown_words',
            field=models.ManyToManyField(blank=True, related_name='unknown_by_users', to='vorp_api.vocabulary'),
        ),
    ]
