# Generated by Django 5.2.3 on 2025-07-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorp_api', '0003_user_unknown_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='baseForm',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.JSONField(default=list),
        ),
    ]
